### ISSUE TITLE
Overview of UWG_Matlab Translation

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/urbanWeatherGen#9]
@chriswmackey 

For the sake of keeping us organized, here's an overview of translation efforts so far. List below are all the .m files from the UWG_Matlab repo. X indicates what's been finished so far. I'll update whenever a file is finished. 

X — 1BEMDef.m
X — 2Material.m
X — 3SchDef.m
X — 4readDOE.m
X — 5SimParam.m
X — 6Weather.m
7UWGParameter.m
8Building.m
9Element.m
10Forcing.m
11InfraCalcs.m
12Param.m
13Psychrometrics.m
14readUWG.m
15RSMDef.m
16SolarCalcs.m
17UBLDef.m
18UCMDef.m
19UrbFlux.m
20Def_Materials.m
21UWG.m
22readEP.m
xml_read.m ?
test_run.m ?
progressbar.m ?

**Comment by chriswmackey** [comment]
Looks good @saeranv .  Thanks for the clarity.

**Comment by saeranv** [comment]
Update:

  X — 1BEMDef.m
XX — 2Material.m
XX — 3SchDef.m
XX — 4readDOE.m
XX — 5SimParam.m
XX — 6Weather.m
XX — 7UWGParameter.m
  X -- 8Forcing.m
XX -- 9Param.m
XX -- 10Psychrometrics.m

11Building.m
12Element.m
13InfraCalcs.m
14readUWG.m
15RSMDef.m
16SolarCalcs.m
17UBLDef.m
18UCMDef.m
19UrbFlux.m
20Def_Materials.m
21UWG.m
22readEP.m

xml_read.m
test_run.m
progressbar.m


XX = Finished & tested
  X = Finished not tested

**Comment by saeranv** [comment]
Done!
